### ISSUE TITLE
Margin arrond buttons

### ISSUE THREAD

**Issue by SebastienTouze** [etalab/template.data.gouv.fr#103]
The button do not have a top/button margin, making them being stuck together when they are on 2 lines. This happen quite often on small / mobile screens.
Maybe changing the button margin to a 0.5 surrounding margin like `margin: 0.5em 0.25em 0.5em 0.25em;` could solve this ?

**Comment by thimy** [comment]
I'm a bit annoyed by this because if your button is aligned on the left, there will be a small gap compared to other elements.

I think I'd rather have a media query with a rule like:
```
.button + .button {
    margin-top: var(--space-s);
}
```

Tell me if that would be satisfactory for you!

**Comment by SebastienTouze** [comment]
Thanks for your answer and yes, indeed that would be great for my issue.

**Comment by thimy** [comment]
That should be handled in the latest version of the package `1.2.2`, let me know if this works.

**Comment by SebastienTouze** [comment]
Sorry for late reply. It's not fully working alas : I tried on large mobile screens / phablets and I get a mix of the 2 margins. 
![image](https://user-images.githubusercontent.com/5538298/59859893-ea250300-937d-11e9-822c-b1623ceed178.png)

Maybe a solution is to delete the 
```
.button + .button, .button-outline + .button-outline {
    margin-left: 1em;
}
``` 
rule and the new media query and only keep a 
```
.button {
  margin-top 0.5em;
  margin-bottom 0.5em;
}
```
Which always adds a top/bottom margin.

I can prepare a PR if it can make things more clear

**Comment by bzg** [comment]
Thanks for the PR! Closing this now.
