### ISSUE TITLE
Add a large desktop screen media query

### ISSUE THREAD

**Issue by SebastienTouze** [etalab/template.data.gouv.fr#104]
Considering that many desktop have a 1920px width, could it be relevant to add a large desktop media query, to make a large .container (like 1340px) for those screen ?

**Comment by thimy** [comment]
The latest version (released yesterday) set the largest media query from 1000px to 1200px, would it be enough or do you wish to have a larger media query specifically?

Thanks for the feedback!

**Comment by SebastienTouze** [comment]
Thanks for the answer and yes, it looks quite good with a 1200px width (so using ~65% of screen size). 
I didn't check the last version this morning before opening the issue, now closing as solved =)
