### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by brindu** [etalab/template.data.gouv.fr#112]
Hello, 

We (API Entreprise) are using the template and we now need pagination for data tables. Is-it something that will be added to the template ?

**Comment by thimy** [comment]
Could it be the same as used in entreprise.data.gouv.fr or do you have something else in mind?

**Comment by brindu** [comment]
Yes sorry for not being specific enough 😅 

First I did not think about the existing pagination on entreprise.data.gouv.fr because we needed pagination for a data table, but I agree we could simply use the existing pagination for a table.

The issue is that we do not only need pagination but also ordering by columns, a research bar for filtering, ... To have it quickly up and running we now use Vuetify for this component only (here is a screenshot).

<img width="1090" alt="Capture d’écran 2019-06-05 à 11 15 18" src="https://user-images.githubusercontent.com/4283958/58928033-754da880-8783-11e9-8854-4ef3c8b9c9f2.png">

So what I have in mind is more like a package of style components for data tables.
