### ISSUE TITLE
Chemin d'import invalide 

### ISSUE THREAD

**Issue by benoitguigal** [etalab/template.data.gouv.fr#128]
### node:10.4-alpine

Dans le README
```
import 'template.data.gouv.fr/dist/style/main.css'
```

Il semblerait que le chemin d'import soit plutôt 

```
template.data.gouv.fr/dist/main.css
```

**Comment by bzg** [comment]
Hello, merci d'avoir signalé le souci, ça a été corrigé dans [https://github.com/etalab/template.data.gouv.fr/commit/38dee8250b5c5a9ab619bec07d97d40cb44d80a0](ce commit).
