### ISSUE TITLE
Exposer comme thème Jekyll

### ISSUE THREAD

**Issue by oncletom** [etalab/template.data.gouv.fr#15]
Intention : utiliser ces templates, ses ressources et bénéficier de ses mises à jour dans des applications [Jekyll](https://jekyllrb.com/docs/themes/).

On gagnerait en maintenance et en facilité de déploiement de nouveaux sites sans avoir trop à s'y connaitre.

- [ ] https://jekyllrb.com/docs/themes/#creating-a-gem-based-theme
- [ ] https://docs.travis-ci.com/user/deployment/rubygems/

**Comment by jdesboeufs** [comment]
Peut-être comme dépôt séparé alors car on risque de faire pareil pour des composants React.
WDYT ?

**Comment by oncletom** [comment]
Dans l'idée chuis dac. En pratique ma crainte c'est qu'en éloignant le code dans des dépôts séparés, ça se désynchronise.

On pourrait déjà démarrer dans des répertoires distincts (genre `html`, `liquid`, `react`) et voir à l'usage si ça fait trop de bruit ; séparer à ce moment.

On piétine(rait ?) pas le travail déjà fait, on peut mettre en commun (assets et feuille de style au moins).

**Comment by thimy** [comment]
Un thème jekyll est disponible en gem ici : https://rubygems.org/gems/jekyll-theme-gouvfr
Il a finalement été fait sur un dépôt séparé pour le moment mais on peut en parler si besoin.

**Comment by bzg** [comment]
Hello, où est le dépôt de code pour la déclinaison `jekyll` de template.data.gouv.fr ?

La page https://rubygems.org/gems/jekyll-theme-gouvfr indique https://template-jekyll.data.gouv.fr comme page d'accueil, mais celle-ci renvoie une erreur.

**Comment by thimy** [comment]
Le dépôt se trouve ici : https://github.com/etalab/template-jekyll
Il est sûrement pas tout à fait à jour par rapport à la dernière release par contre !
