### ISSUE TITLE
Le symbole `icon-rss` est initialisé deux fois

### ISSUE THREAD

**Issue by Flightan** [etalab/template.data.gouv.fr#23]
https://github.com/etalab/template.data.gouv.fr/blob/e83093835e50b5e6363bf5fa95d867ccf4c92248/index.html#L73

**Comment by gregoirenovel** [comment]
Fait dans 7019eb68df54e1fdf9df4da22c9f0ce8e857548b

@Flightan je ne peux pas fermer l'issue, je te laisse le faire
