### ISSUE TITLE
Renommer la partie "documentation"

### ISSUE THREAD

**Issue by Flightan** [etalab/template.data.gouv.fr#45]
Je pense qu'il faudrait plutôt partir sur quelque chose comme `with-side-panel`. On compte par exemple l'utiliser pour un formulaire un peu long.

**Comment by thimy** [comment]
J'étais en train de me poser la question de faire une différente version qui serait plutôt dédiée à ce qui ressemble à un dashboard, je me suis rendue compte en faisant l'espace client que certaines choses qui me convenait pour de la doc n'allait pas pour un tableau de bord, ça te paraitrait déconnant ?

**Comment by Flightan** [comment]
Non ça semble bien mais dans https://github.com/etalab/template.data.gouv.fr/blob/master/src/css/documentation.css je ne vois que le code pour les deux panels (`side-pane` et `main-pane`). Tu pensais changer quoi ?

**Comment by thimy** [comment]
Du coup je ferme !
