### ISSUE TITLE
Nouvelle couleur « rouge lie de vin » ?

### ISSUE THREAD

**Issue by bzg** [etalab/template.data.gouv.fr#68]
Hello @thimy ! Avec @milkosofi nous avions besoin d'une autre couleur que le rose et le orange pour le futur site EIG, nous avons opté pour un rouge « lie de vin »: #b41818 ou #a01616 en plus clair.

C'est visible sur le logo pour l'instant: http://site-eig.etalab.gouv.fr

Est-ce que tu penses que cela pourrait avoir vocation à être intégré au template? 

Bonnes vacances, à bientôt !

**Comment by thimy** [comment]
Hello !

Oui je peux la rajouter, tu en as besoin pour quoi exactement ?

**Comment by bzg** [comment]
Merci pour ta réponse ! Pour l'instant nous l'avons utilisé seulement pour le rouge du logo : http://site-eig.etalab.gouv.fr/images/logo-bordered.png

Mais nous l'utiliserons peut-être pour d'autres éléments, à voir.

**Comment by bzg** [comment]
@milkosofi I think we can close this issue - agreed?

**Comment by bzg** [comment]
Agreed and closing.
